const express = require('express')
const userAuth = express.Router()
const { singUpValidation, Signup } = require('../controller/signup')
const { login, loginVerify } = require('../controller/login')
const { userVerify, verify } = require('../controller/auth')
const { logout } = require('../controller/logout')
const { AllUser, userProfile } = require('../controller/all_user')
const { newchat, chatList } = require('../controller/chatAPI')
userAuth.post('/signup', singUpValidation, Signup)
userAuth.post('/login', loginVerify, login)
userAuth.get('/verify', verify, userVerify)
userAuth.get('/logout', logout)
userAuth.get('/all_User', verify, AllUser)
userAuth.get('/profile', userProfile)
userAuth.post('/newchat', newchat)
userAuth.get('/userChat', chatList)

module.exports = userAuth